f=open("demo.txt","r")
print(f.read())
print(type(f.read()))
f.close()
f=open("demo.txt")
text=f.readline()
print(text)
f.close()
f=open("demo.txt","w")
f.write("Hello brothers")
f.close()
f=open("demo.txt")
print(f.read())
f.close()
f=open("demo.txt","a")
text=f.write("and sisters")
f.close()
f=open("demo.txt","r")
print(f.read())
f.close()
f=open("demo.txt","a")
text=f.write("\nand sisters")
f.close()
f=open("demo.txt","r")
print(f.read())